# Generated by Django 5.0.3 on 2024-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_accessories_alter_fueling_options_alter_fueling_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessories',
            new_name='Accessory',
        ),
    ]
